### ISSUE TITLE
Sales channel token renew results in ClientOAuth2Token exception

### ISSUE THREAD

**Issue by citlacom** [commercelayer/commercelayer-js-auth#17]
We are trying to renew the webapp sales token after expiration with the code recipe provided by @pviti

```
const token = await getSalesChannelToken({
 clientId,
 endpoint,
 scope,
})
const newToken = await token.refresh()
```

However, by trying this we got the following error:

```
Error: No refresh token
        at ClientOAuth2Token.Object.<anonymous>.ClientOAuth2Token.refresh (/Users/pablocc/Sites/therefore/trudmw-web-gat/node_modules/client-oauth2/src/client-oauth2.js:373:27)
        at /Users/pablocc/Sites/therefore/trudmw-web-gat/web/commercelayer/actions/AuthActions.js:70:35
        at Generator.next (<anonymous>)
        at fulfilled (/Users/pablocc/Sites/therefore/trudmw-web-gat/web/commercelayer/dist/cjs/actions/AuthActions.js:13:24)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Inspecting the response from "getSalesChannelToken" call we noted that the "refreshToken" is set as "undefined":

![Screenshot 2021-11-23 at 16 50 46](https://user-images.githubusercontent.com/802425/143057496-841f93e9-2234-46c0-ba67-b8c18506665d.png)

I think this is a problem in the JS Auth library that is not passing this refresh token in the creation of "ClientOAuth2Token" object. Can you help us with a solution to renew the sales token. Thanks!

**Comment by pviti** [comment]
Hi @citlacom , sorry but I gave you a partially wrong suggestion: to have the `refresh_token` field filled in you must use `sales_channel` with customer credentials:

```
const token = await getSalesChannelToken({
 clientId,
 endpoint,
 scope,
}, {
  username: customer_email,
  password: customer_password
})
```

In this way you'll get a data object like the following:

```
data: {
    access_token: 'eyJhbGciOiJIUzUxMiJ9.eyJvcmdhbml6YXRpb24iOnsiaWQiO........',
    token_type: 'Bearer',
    expires_in: 13968,
    refresh_token: 'rse-idKrrpVqqE7LzraSN9JhnGTiELRg6X1TSps3UgA',
    scope: 'market:4426',
    created_at: 1637685604,
    owner_id: 'OyqghBByvW',
    owner_type: 'customer'
  },
```

**Comment by acasazza** [comment]
Hi @citlacom!

I've updated types to avoid a misunderstanding 🙌🏻
